// <auto-generated />
namespace UniversityCourseAndResultManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Course_v6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Course_v6));
        
        string IMigrationMetadata.Id
        {
            get { return "201912210715572_Course_v6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
