// <auto-generated />
namespace UniversityCourseAndResultManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Teacher_V4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Teacher_V4));
        
        string IMigrationMetadata.Id
        {
            get { return "201912222326551_Teacher_V4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
